feat: change download button colors
flybywiresim/flybywiresim-website pull request #51
Opened 2021-02-09 20:18 UTC by armankir

I changed the download button colors and hover states.

BEFORE: 
![image](https://user-images.githubusercontent.com/70278701/107423231-16a90800-6aea-11eb-93bc-989470f5b442.png)

AFTER:
![image](https://user-images.githubusercontent.com/70278701/107423255-1e68ac80-6aea-11eb-9042-6ece4f85cf5d.png)

2021-02-09 20:25 UTC, Valastiri commented
What if the bottom two (dev and cFBW) were #6399AE instead for color. 

Now it's just doubly bright across the board.

2021-02-10 22:53 UTC, NathanInnes commented
On hold until more feedback comes through.

2021-02-11 13:16 UTC, NathanInnes approved these changes

2021-02-11 13:18 UTC, NathanInnes requested changes

2021-02-11 13:18 UTC, NathanInnes commented on src/components/app/Download.tsx
> +                                            <Button className="w-40 float-right bg-blue-light-contrast AE hover:bg-blue-medium font-bold">Download</Button>
'AE' should not be there.

2021-02-11 13:41 UTC, NathanInnes approved these changes

2021-02-11 13:41 UTC, merged